import Header from "./header"
import Footer from "./footer"
import Navigate from "./navigate"
import NewsCard from "./news-card"
import ProductsCard from "./products-card"
import TopShop from "./topshop-card"
import AdvCard from "./adventage_card"
import CatalogCard from "./catalog-card"
import ProductCard from "./porduct-card"
export {Header, Footer ,Navigate,NewsCard ,ProductsCard ,TopShop ,AdvCard , CatalogCard,ProductCard}